import { type CodeJSON } from "../schema/cms.js";

// CMS variant skeleton of code.json (gov-codejson CMS schema)
export const cmsBaselineCodeJSON: Partial<CodeJSON> = {
  name: "",
  version: "",
  description: "",
  longDescription: "",
  status: undefined,
  permissions: {
    licenses: [],
    usageType: [],
    exemptionText: "",
  },
  organization: undefined,
  repositoryURL: "",
  repositoryHost: undefined,
  repositoryVisibility: undefined,
  homepageURL: "",
  downloadURL: "",
  disclaimerURL: "",
  disclaimerText: "",
  vcs: "git",
  laborHours: 0,
  reuseFrequency: {
    forks: 0,
    clones: 0,
  },
  platforms: [],
  categories: [],
  softwareType: undefined,
  languages: [],
  maintenance: undefined,
  contractNumber: [],
  SBOM: "",
  relatedCode: [],
  reusedCode: [],
  partners: [],
  date: {
    created: "",
    lastModified: "",
    metadataLastUpdated: "",
  },
  tags: [],
  contact: {
    email: "",
    name: "",
  },
  feedbackMechanism: "",
  AIUseCaseID: "0",
  localisation: false,
  repositoryType: undefined,
  userInput: false,
  fismaLevel: undefined,
  group: "",
  projects: [],
  systems: [],
  subsetInHealthcare: [],
  userType: [],
  maturityModelTier: 0,
};
